[launch] change `MakeGoodLaunchConfigurationDelegate` to use own `getDebuggerConfiguration()` instead of `PHPDebuggersRegistry.getDebuggerConfiguration()` #77
This changes will avoid `java.lang.NoSuchMethodError` as the following:

java.lang.NoSuchMethodError: org.eclipse.php.internal.debug.core.preferences.PHPDebuggersRegistry.getDebuggerConfiguration(Ljava/lang/String;)Lorg/eclipse/php/internal/debug/core/debugger/AbstractDebuggerConfiguration;
	at com.piece_framework.makegood.launch.MakeGoodLaunchConfigurationDelegate.rewriteBasicConfigurationAttributes(MakeGoodLaunchConfigurationDelegate.java:290)
	at com.piece_framework.makegood.launch.MakeGoodLaunchConfigurationDelegate.createConfiguration(MakeGoodLaunchConfigurationDelegate.java:268)
	at com.piece_framework.makegood.launch.MakeGoodLaunchConfigurationDelegate.getLaunch(MakeGoodLaunchConfigurationDelegate.java:86)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:812)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)